# Generated by Django 4.0.2 on 2022-02-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionapi', '0003_alter_category_options_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=32),
        ),
    ]
